/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Account_Info: typeof import('./src/components/Account/Account_Info.vue')['default']
    BButton: typeof import('bootstrap-vue-next')['BButton']
    BCard: typeof import('bootstrap-vue-next')['BCard']
    BCol: typeof import('bootstrap-vue-next')['BCol']
    BCollapse: typeof import('bootstrap-vue-next')['BCollapse']
    BContainer: typeof import('bootstrap-vue-next')['BContainer']
    BDropdown: typeof import('bootstrap-vue-next')['BDropdown']
    BDropdownItem: typeof import('bootstrap-vue-next')['BDropdownItem']
    BFormFile: typeof import('bootstrap-vue-next')['BFormFile']
    BFormInput: typeof import('bootstrap-vue-next')['BFormInput']
    BFormTextarea: typeof import('bootstrap-vue-next')['BFormTextarea']
    BImg: typeof import('bootstrap-vue-next')['BImg']
    BLink: typeof import('bootstrap-vue-next')['BLink']
    BModal: typeof import('bootstrap-vue-next')['BModal']
    BNavbar: typeof import('bootstrap-vue-next')['BNavbar']
    BNavbarBrand: typeof import('bootstrap-vue-next')['BNavbarBrand']
    BNavbarNav: typeof import('bootstrap-vue-next')['BNavbarNav']
    BNavbarToggle: typeof import('bootstrap-vue-next')['BNavbarToggle']
    BNavForm: typeof import('bootstrap-vue-next')['BNavForm']
    BNavItem: typeof import('bootstrap-vue-next')['BNavItem']
    BPagination: typeof import('bootstrap-vue-next')['BPagination']
    BRow: typeof import('bootstrap-vue-next')['BRow']
    BSpinner: typeof import('bootstrap-vue-next')['BSpinner']
    Deep_Learning: typeof import('./src/components/Deep_Learning.vue')['default']
    Header: typeof import('./src/components/Header.vue')['default']
    IBiCardList: typeof import('~icons/bi/card-list')['default']
    IBiEmojiSunglasses: typeof import('~icons/bi/emoji-sunglasses')['default']
    IBiFileExcelFill: typeof import('~icons/bi/file-excel-fill')['default']
    IBiHandThumbsUpFill: typeof import('~icons/bi/hand-thumbs-up-fill')['default']
    IBiKeyFill: typeof import('~icons/bi/key-fill')['default']
    IBiLightningFill: typeof import('~icons/bi/lightning-fill')['default']
    IBiPostageFill: typeof import('~icons/bi/postage-fill')['default']
    Login: typeof import('./src/components/Account/Login.vue')['default']
    Main_Page: typeof import('./src/components/Main_Page.vue')['default']
    Post_Create_Update: typeof import('./src/components/Community/Post_Create_Update.vue')['default']
    Post_Detail: typeof import('./src/components/Community/Post_Detail.vue')['default']
    Post_List: typeof import('./src/components/Community/Post_List.vue')['default']
    Register: typeof import('./src/components/Account/Register.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
  export interface ComponentCustomProperties {
    vBColorMode: typeof import('bootstrap-vue-next')['vBColorMode']
  }
}
