"""3

Revision ID: a9eda6b4c43f
Revises: 449602c0b454
Create Date: 2024-01-12 17:44:16.753427

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'a9eda6b4c43f'
down_revision: Union[str, None] = '449602c0b454'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'temp')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('temp', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
